version: '3.7'
services:
  ferengi-mongo:
    container_name: ferengi-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    logging:
      driver: none
    networks:
      docker-net:

  ferengi-app:
    container_name: ferengi-app
    image: node:14
    ports:
      - 8080:8080
    working_dir: /var/app/ferengi
    volumes:
      - .:/var/app/ferengi
    environment:
      - NODE_CONFIG_DIR=./config
      - NODE_ENV=docker
      - PATH=./node_modules/.bin:${PATH}
    depends_on:
      - ferengi-mongo
    command: "node -r ts-node/register ./src/index.ts"
    networks:
      docker-net:

networks:
  docker-net: